#!/bin/bash
caller=$1
contract=$2
tonic_contract=$3
amount=$4

near call $contract ft_transfer_call \
    '{"receiver_id":"'$tonic_contract'", "amount": "'$amount'", "msg": ""}' \
    --accountId $caller \
    --depositYocto 1 \
    --gas 300000000000000

