#!/bin/bash
near call $DEV_QUOTE_TOKEN_ID \
    storage_deposit \
    '{"account_id":"'$NEAR_ACCOUNT_ID'","registration_only":true}' \
    --deposit 0.1 \
    --accountId $NEAR_ACCOUNT_ID

near call $DEV_BASE_TOKEN_ID \
    storage_deposit \
    '{"account_id":"'$NEAR_ACCOUNT_ID'","registration_only":true}' \
    --deposit 0.1 \
    --accountId $NEAR_ACCOUNT_ID

